### ISSUE TITLE
SOLVED: Docker Build hanging at Java ca-certification

### ISSUE THREAD

**Issue by JJediny** [GSA/catalog-app#11]
*Using Mac OSx El Captain w Docker Toolkit*
After a long read figured out this was an issue with the virtualbox only having 1cpu... stoping vm and allocating 2cpu avoids hanging on java build:
https://github.com/docker/docker/issues/18180

Should #2 isolate tomcat/fgdc2iso as its own container and may be a good candidate for building through cloud foundry separately as Java apps seem to be better supported via cf over docker

**Comment by kenden** [comment]
This should be fixed by this commit: https://github.com/boot2docker/boot2docker/commit/332e7a493b0843b17a85dd0ba2ebda38d018f04d
