### ISSUE TITLE
Sidepane/Leaflet spatial-query CSS issue

### ISSUE THREAD

**Issue by JJediny** [GSA/catalog-app#20]
looks like `leaflet-map-pane` is resizing from -3px to -38 causing the sidepane to appear truncated...

<img width="925" alt="screen shot 2016-02-12 at 1 19 54 pm" src="https://cloud.githubusercontent.com/assets/6350035/13016291/bd2a6762-d18b-11e5-8505-474dcce66aba.png">
<img width="895" alt="screen shot 2016-02-12 at 1 20 06 pm" src="https://cloud.githubusercontent.com/assets/6350035/13016293/bdf66eb6-d18b-11e5-8cbb-14e96dc2092b.png">

**Comment by KapilBulchandani-REISys** [comment]
Fixed the resize issue by adding width.
https://github.com/GSA/ckanext-datagovtheme/commit/458819c97b8c0afac561859f499e1e628190808b
