### ISSUE TITLE
Installation documentation is (somewhat) terse...

### ISSUE THREAD

**Issue by infracritical** [GSA/catalog-app#203]
Hello, I'd like to utilize the 'catalog.data.gov' website for non-profit, free, research purposes. The project is called 'SCIDMARK', and deals with setting up a comprehensive system and cyber operational impact database. I feel that this will become beneficial for everyone. I've decided to use CKAN as the method of data distribution; however, nothing thus far has worked.

I reviewed the README.md and have tried (as best as possible) to understand the method of installation. Much of what has been typed is implied. Thus, why I am seeking help.

Is there a more comprehensive step-by-step guide for installing and configuring your website?

Of course, I will give credit where credit is due.

I am seeking help from anyone who has SUCCESSFULLY installed this application for this website with its customizations, et. al.  Please help. This will greatly benefit everyone once implemented.

If you decide to answer offline, I may be reached at rsradvan@infracritical.com. 

Thank you.

**Comment by jbrown-xentity** [comment]
Thanks for reaching out!
A new build of our catalog site is located at https://github.com/gsa/catalog.data.gov. This contains a more robust README for local development. Please open a ticket there if you are having trouble implementing or using that code.
