### ISSUE TITLE
Catalog-app Testing All Processes

### ISSUE THREAD

**Issue by JJediny** [GSA/catalog-app#21]
I added a few and removed one duplicate from the top list. The last two (combine-feeds and export-csv) are extracted from Frontend instance crons. They contain some hard coded file names as output. So it will run into file path issue if run as it is. 
- [x] `docker-compose run app` *ckan --plugin=ckanext-harvest harvester run*
>Start any pending harvesting jobs

- [x] `docker-compose run app` *ckan --plugin=ckanext-geodatagov geodatagov harvest-job-cleanup*
>Harvest jobs can get stuck at Running state and stay that way forever. This will reset them and fix any harvest object issues they cause. 

- [x] `docker-compose run app` *ckan --plugin=ckanext-qa qa update_sel*
>Start QA analysis on all datasets whose 'last modified timestamp' is >= timestamp embedded in the following file: /var/log/qa-metadata-modified.log

- [x] `docker-compose run app` *ckan --plugin=ckanext-qa qa collect-ids && ckan --plugin=ckanext-qa qa update*
>Compare to qa update_sel, this qa update will run analysis on ALL datasets. It will take loooooooong to finish.

- [x] `docker-compose run app` *ckan --plugin=ckanext-geodatagov geodatagov clean-deleted*
>CKAN keeps deleted package in the DB. This clean command makes sure they are really gone.

- [x] `docker-compose run app` *ckan tracking update*
>This needs to be run periodically in order to run analysis on raw data and generate summarised page view tracking data that ckan/solr can use.

- [x] `docker-compose run app` *ckan --plugin=ckanext-report report generate*
>This generates /report/broken-links page showing broken link statistics for dataset resources by organization.

- [x] `docker-compose run app` *ckan --plugin=ckanext-geodatagov geodatagov db_solr_sync*
>Over time solr can get out of sync from db due to all kind of glitches. This brings them back in sync. 

- [x] `docker-compose run app` *ckan --plugin=ckanext-spatial ckan-pycsw set_keywords -p /etc/ckan/pycsw-collection.cfg*
>This grabs top 20 tags from CKAN and put them into /etc/ckan/pycsw-collection.cfg as CSW service metadata keywords.

- [x] `docker-compose run app` *ckan --plugin=ckanext-spatial ckan-pycsw set_keywords -p /etc/ckan/pycsw-all.cfg*
>This grabs top 20 tags from ckan and put them into /etc/ckan/pycsw-all.cfg as CSW service metadata keywords.

- [x] `docker-compose run app` *ckan --plugin=ckanext-spatial ckan-pycsw load -p /etc/ckan/pycsw-all.cfg*
>Accesses CKAN api to load CKAN datasets into pycsw database.
>This funciton has been taken out of catalog-app and moved to catalog-pycsw service.

- [x] `docker-compose run app` */usr/lib/ckan/bin/pycsw-db-admin.py vacuumdb /etc/ckan/pycsw-all.cfg*
>Does vacuumdb job on pycsw database.
>This funciton has been taken out of catalog-app and moved to catalog-pycsw service.

- [x] `docker-compose run app` */usr/lib/ckan/bin/pycsw-db-admin.py reindex_fts /etc/ckan/pycsw-all.cfg*
>Rebuilds GIN index on pycsw records table to speed up full text search.
>This funciton has been taken out of catalog-app and moved to catalog-pycsw service.

- [x] `docker-compose run app` *ckan --plugin=ckanext-geodatagov geodatagov combine-feeds*
>This gathers 20 pages of CKAN feeds from /feeds/dataset.atom and generates /usasearch-custom-feed.xml to feed USAsearch. USAsearch uses Bing index as backend which does not understand pagination in atom feeds.

- [x] `docker-compose run app` *ckan --plugin=ckanext-geodatagov geodatagov export-csv*
>This keeps records of all datasets that are tagged with Topic and Topic Categories, and generates /csv/topic_datasets.csv

**Comment by dano-reisys** [comment]
to run any ckan command:
# docker-compose run app {command}

i.e. 
# docker-compose run app ckan --plugin=ckanext-qa qa update_sel

**Comment by JJediny** [comment]
Consolidated CMD(s) 
```
date && echo "0. start collecting"
top -bc > /tmp/top.log & toptaskid=$!
sleep 10

date && echo "1. running tracking update for 30 sec..."
ckan tracking update >> /tmp/tasks.log 2>&1 & taskid=$!
sleep 30; kill $taskid 2> /dev/null; sleep 10

date && echo "2. running qa update_sel for 30 sec..."
ckan --plugin=ckanext-qa qa update_sel >> /tmp/tasks.log 2>&1 & taskid=$!
sleep 30; kill $taskid 2> /dev/null; sleep 10

date && echo "3. running report generate for 30 sec..."
ckan --plugin=ckanext-report report generate >> /tmp/tasks.log 2>&1 & taskid=$!
sleep 30; kill $taskid 2> /dev/null; sleep 10

date && echo "4. running db_solr_sync for 30 sec..."
ckan --plugin=ckanext-geodatagov geodatagov db_solr_sync >> /tmp/tasks.log 2>&1 & taskid=$!
sleep 30; kill $taskid 2> /dev/null; sleep 10

date && echo "5. running harvest-job-cleanup for 30 sec..."
ckan --plugin=ckanext-geodatagov geodatagov harvest-job-cleanup >> /tmp/tasks.log 2>&1 & taskid=$!
sleep 30; kill $taskid 2> /dev/null; sleep 10

date && echo "6. running ckan-pycsw set_keywords pycsw-collection for 30 sec..."
/usr/lib/ckan/bin/paster --plugin=ckanext-spatial ckan-pycsw set_keywords -p /etc/ckan/pycsw-collection.cfg >> /tmp/tasks.log 2>&1 & taskid=$!
sleep 30; kill $taskid 2> /dev/null; sleep 10

date && echo "7. running ckan-pycsw set_keywords pycsw-all for 30 sec..."
/usr/lib/ckan/bin/paster --plugin=ckanext-spatial ckan-pycsw set_keywords -p /etc/ckan/pycsw-all.cfg >> /tmp/tasks.log 2>&1 & taskid=$!
sleep 30; kill $taskid 2> /dev/null; sleep 10

date && echo "8. running ckan-pycsw load for 30 sec..."
/usr/lib/ckan/bin/paster --plugin=ckanext-spatial ckan-pycsw load -p /etc/ckan/pycsw-all.cfg >> /tmp/tasks.log 2>&1 & taskid=$!
sleep 30; kill $taskid 2> /dev/null; sleep 10

date && echo "9. running ckan-pycsw vacuumdb for 30 sec..."
/usr/lib/ckan/bin/python /usr/lib/ckan/bin/pycsw-db-admin.py vacuumdb /etc/ckan/pycsw-all.cfg >> /tmp/tasks.log 2>&1 & taskid=$!
sleep 30; kill $taskid 2> /dev/null; sleep 10

date && echo "10. running ckan-pycsw reindex_fts for 30 sec..."
/usr/lib/ckan/bin/python /usr/lib/ckan/bin/pycsw-db-admin.py reindex_fts /etc/ckan/pycsw-all.cfg >> /tmp/tasks.log 2>&1 & taskid=$!
sleep 30; kill $taskid 2> /dev/null; sleep 10

date && echo "11. running harvesting for 30 sec..."
ckan --plugin=ckanext-harvest harvester run >> /tmp/tasks.log 2>&1 & taskid=$!
sleep 30; kill $taskid 2> /dev/null; sleep 10

kill $toptaskid
```

**Comment by dano-reisys** [comment]
@FuhuXia are we missing any commands?

**Comment by JJediny** [comment]
Harvester output...
https://gist.github.com/JJediny/344bb7d3e049155b17ac

**Comment by FuhuXia** [comment]
I added a few and removed one duplicate from the top list. The last two (combine-feeds and export-csv) are extracted from Frontend instance crons. They contain some hard coded file names as output. So it will run into file path issue if run as it is. 

- [ ] ckan --plugin=ckanext-harvest harvester run
- [ ] ckan --plugin=ckanext-geodatagov geodatagov harvest-job-cleanup
- [ ] ckan --plugin=ckanext-qa qa update_sel
- [ ] ckan --plugin=ckanext-geodatagov geodatagov clean-deleted
- [ ] ckan tracking update
- [ ] ckan --plugin=ckanext-qa qa collect-ids && ckan --plugin=ckanext-qa qa update
- [ ] ckan --plugin=ckanext-report report generate
- [ ] ckan --plugin=ckanext-geodatagov geodatagov db_solr_sync
- [ ] ckan --plugin=ckanext-spatial ckan-pycsw set_keywords -p /etc/ckan/pycsw-collection.cfg
- [ ] ckan --plugin=ckanext-spatial ckan-pycsw set_keywords -p /etc/ckan/pycsw-all.cfg
- [ ] ckan --plugin=ckanext-spatial ckan-pycsw load -p /etc/ckan/pycsw-all.cfg
- [ ] /usr/lib/ckan/bin/python /usr/lib/ckan/bin/pycsw-db-admin.py vacuumdb /etc/ckan/pycsw-all.cfg
- [ ] /usr/lib/ckan/bin/python /usr/lib/ckan/bin/pycsw-db-admin.py reindex_fts /etc/ckan/pycsw-all.cfg
- [ ] ckan --plugin=ckanext-geodatagov geodatagov combine-feeds
- [ ] ckan --plugin=ckanext-geodatagov geodatagov export-csv

**Comment by dano-reisys** [comment]
@FuhuXia can we include a short description of what each command does? I'll add the descriptions for the commands that i am familiar with

**Comment by FuhuXia** [comment]
all processes have to put into https://github.com/GSA/catalog-scheduler/blob/master/crontab.
