### ISSUE TITLE
Need help ingesting data.json

### ISSUE THREAD

**Issue by dportnoy** [GSA/catalog-app#24]
Now that I have the docker container live, I need help ingesting a data.json to get going.  Can somebody provide step by step instructions?

**Comment by dano-reisys** [comment]
David, you would need to 

1- create a sysadmin user: `docker-compose run app ckan sysadmin add some_user`
2- create an organization: `/organization/new`
3- create a harvest source: `/harvest/new` with a datajson endpoint i.e: `http://www.consumerfinance.gov/data.json` and source type: `/data.json`
4- click on `reharvest` button on the newly created harvest source admin page
5- crond should be able to initiate the harvesting job, if it doesn't run:
`docker-compose run app ckan --plugin=ckanext-harvest harvester run`

**Comment by dportnoy** [comment]
Thanks @dano-reisys and @JJediny for providing additional instruction!  Here's my writeup of the process.  Let me know if I left out anything...
______

- Create a sysadmin user:
   ``` bash
   docker-compose run app ckan sysadmin add some_user
   ```

- Through a web browser… 
    - Go to __{base_url}/login__ and login as a sysadmin user
    - Go to __{base_url}/organization/new__ and create a new organization
    - Go to __{base_url}/harvest/new__ and create a new data.json source.
    - Specify data.json endpoint URL
    - Specify source type: /data.json
    - Click “Save”, “Admin”, “Reharvest” on the newly created harvest source admin page

- The harvest Cron job runs every 3 minutes.  But you can launch it immediately…

   ```bash
   docker exec -it apps_app_1 /bin/bash
   ckan --plugin=ckanext-harvest harvester run
   ```
 
- For large data.json ingestions, consider scaling up the number of harvester containers…

   ``` bash
   docker-compose scale harvester-fetch-consumer=10
   ```

**Comment by JJediny** [comment]
Should all now be in README thanks @dpomeroy

**Comment by dpomeroy** [comment]
@dportnoy
not @dpomeroy 
=-D  Thanks!

**Comment by dportnoy** [comment]
Looks like also covered in detail by @JJediny in #26 "Document workflow to edit data.json".  Thanks!
