### ISSUE TITLE
Document workflows for common development tasks

### ISSUE THREAD

**Issue by dportnoy** [GSA/catalog-app#27]
It would be beneficial to have instructions with examples of how one would go about making certain changes...

**1. How to make a code or config change for items under the "docker" folder, such that they persist.**
_(This would include configuration and commands necessary for linking volumes and location of git repositories.)_

**2. How to make a code or config change for items not under the Docker/ folder, such that they are picked up by the running docker-compose and persist after the container goes down.**
_(This would include configuration and commands necessary for linking volumes, clearing cache, rebuilding, and location of git repositories.)_

**3. How to configure Postgres and Solr so that the data persists after the container goes down.**
_(This would include configuration and commands necessary for linking volumes to datastore locations.)_

**Comment by dportnoy** [comment]
The persistent datastore capability in item 3 above has been addressed by commit ec13d71, which defines data volumes in Dockerfile and docker-compose.  

* [ ] Provide additional precautions around using this configuration.  For example, be careful not to launch multiple instances of docker compose, since that would instantiate a new DB. 
* [ ] Provide instructions on the most appropriate way to stop the docker compose to prevent destruction of the persistent store.
* [ ] Identify under which situations might you want to kill docker compose or individual docker containers.  (For example, certain types of coding changes, configuration of docker compose, dockerfile, etc.)

**Comment by dano-reisys** [comment]
I've just added the documentation for OSX: https://github.com/GSA/catalog-app/blob/master/README.md#developing-on-osx

The same concept should work on linux with slight modifications (the pre-requisites part will need to be re-written)
