### ISSUE TITLE
Resolving database inconsistencies

### ISSUE THREAD

**Issue by dportnoy** [GSA/catalog-app#29]
I had problems harvesting data.json today with the latest catalog-app distribution. 

Background...  I originally installed the catalog-app distro a couple weeks ago, when persistent store for postgresql, solr and ckan files wasn't configured.  I recently pulled the new configuration and executed "docker-compose up".  The result...

The result... CKAN seems to be working, but in some funky state.  The data originally harvested was blown away, due to not having persistent store previously.  But looks like the admin user and organization have been saved.  Going to the "/harvest" URL indicated no harvesters, but when I tried to add one, I got an error that the URL is already being harvested.  So I'm assuming the DB is somehow in an inconsistent state.  (While it's not seeing harvesters, it's seeing previously registered harvest URLs.)

So two questions:
1. What's the easiest solution to this problem?
2. What's the most efficient way to start with a clean CKAN DB? 

cc: @JJediny

**Comment by dportnoy** [comment]
This issue should be low priority or closed.  It might be a one-off problem that doesn't affect anyone else.  I think it was just a transitional issue when migrating to a version that configures persistent store.  Basically, the datasets in Solr were blown away, but some of the data in Postgres (users, orgs, harvesters) remained.  I had one other issue with harvesters not showing up in Postgres, but I was able to hack a fix to it.

However, I still think it would be useful to provide instructions for restarting with a clean Solr and Postgres schema, in case data gets corrupted.

**Comment by dano-reisys** [comment]
the db error that has to do with adding the geo.gov user while running "ckan db init" command is related to a ckan core bug. Also the other db issues should be fixed.
