### ISSUE TITLE
refactor geodatagov combine-feeds

### ISSUE THREAD

**Issue by dano-reisys** [GSA/catalog-app#32]
Refactor `geodatagov combine-feeds` command so that it becomes container friendly
full command: `docker-compose run app ckan --plugin=ckanext-geodatagov geodatagov combine-feeds`

**Comment by FuhuXia** [comment]
completed in https://github.com/GSA/ckanext-geodatagov/commit/65d40d9a746beec75561ce20c20859f0a0d9ba7b. Now the generated content is in database instead of local file.
