### ISSUE TITLE
CSS/JS inline issue with Main Banner

### ISSUE THREAD

**Issue by JJediny** [GSA/catalog-app#4]
div class "tooltip fade in/out" causes the banner to break and <li> to display erratically...

![image](https://cloud.githubusercontent.com/assets/6350035/11791890/5eb41b40-a271-11e5-95ae-b87a59dd7a87.png)

**Comment by dano-reisys** [comment]
@KapilBulchandani-REISys is this related to the datagovtheme extension ( https://github.com/GSA/ckanext-datagovtheme/tree/2.3-upgrade) ?
