### ISSUE TITLE
csw harvesting is not working on CKAN 2.3

### ISSUE THREAD

**Issue by kvuppala** [GSA/catalog-app#44]
need to review the error log for csw harvesting and resolve the issue on CKAN 2.3

**Comment by FuhuXia** [comment]
this has been resolved in commit https://github.com/GSA/OWSLib/commit/3352200ad45fcfbe6aa9192ec7f83baf735f67f4. it is a bug from upstream and will submit a pull request.

**Comment by FuhuXia** [comment]
it turns out /geopython/OWSLib has it fixed in version 0.9.0. We are using 0.8.6 because of ckanext-spatial. Let us keep the fix local, no need to push upstream.
