### ISSUE TITLE
refactor install.sh

### ISSUE THREAD

**Issue by dano-reisys** [GSA/catalog-app#8]
remove the 3 line hack at the end of the install.sh script. This might need a fix @ https://github.com/GSA/ckanext-extlink

**Comment by dano-reisys** [comment]
@FuhuXia @kvuppala  can we move this code somewhere else? 
https://github.com/GSA/catalog-app/blob/master/install.sh#L24-L26

or fix it in the extension.

**Comment by FuhuXia** [comment]
it has been addressed in https://github.com/GSA/ckanext-datagovtheme/commit/04d0a026e718e201d826e9fa2a7acd7cc3fb1ef6

**Comment by dano-reisys** [comment]
`OSError: [Errno 13] Permission denied: '/var/tmp/ckan/dynamic_menu/'`
@fxia can we fix this be fixed in the code?

**Comment by FuhuXia** [comment]
can you check the permission for /var/tmp/ckan/, and make sure it was created with proper user/permission.
